GET http://localhost:3000


###
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjEyNzMzMjA0LCJleHAiOjE2MTI4MTk2MDR9.HVhkMVMiZiUvAAYpXfJLk8wHXuOPxgH-MDFOf6G9OYg

###
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "mateusz@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/auth/refresh
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjEyNzMzMzczLCJleHAiOjE2MTMyNTg5NzN9.PdBJg6yAaQG5otKm01K2hbnjoBKviN0AuVY_EIlDX4k"
}